version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_network

  app:
    image: taskmanagementsystem:latest
    container_name: task_management_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - task_network

volumes:
  postgres_data:

networks:
  task_network:
    driver: bridge