spring:
  application:
    name: taskmanagementsystem
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task_management}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always
server:
  error:
    include-stacktrace: on_param
jwt:
  secret: your-256-bit-secret-1234567890abcdef1234567890abcdef
  lifetime: 50m