spring:
  application:
    name:
      taskmanagementsystem
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/task_management}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        show_sql: false
        format_sql: true
server:
  error:
    include-stacktrace: never